apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end2-deployment
  namespace: ahmedcano-dev
  labels:
    app: back-end2
    app.kubernetes.io/component: back-end2
    app.kubernetes.io/instance: back-end2
    app.kubernetes.io/part-of: phase-3-git-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end2
  template:
    metadata:
      labels:
        app: back-end2
        app.kubernetes.io/component: back-end2
    spec:
      containers:
        - name: back-end2
          image: image-registry.openshift-image-registry.svc:5000/ahmedcano-dev/back-end2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
            - name: PORT
              value: "8001"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
           httpGet:
           path: /api/health  
           port: 8001
           initialDelaySeconds: 5
           periodSeconds: 10
           timeoutSeconds: 5
           successThreshold: 1
           failureThreshold: 3

